backup:
  folders:
    # Where the compressed backup files will be stored
    destination: ~/Desktop
    # Folders to compress (backup)
    source:
      - ~/Dropbox
      - path: ~/Projects/company/my-web-project
        name: my-web-project
  camera-uploads:
    sources:
      - "~/Dropbox/Camera Uploads"
      - "~/Dropbox/Camera Uploads from Friend"
    destinations:
      - ~/GooglePhotos/Sync
      - /Volumes/MyExternalDrive/Path